# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainDlg(object):
    def setupUi(self, MainDlg):
        MainDlg.setObjectName("MainDlg")
        MainDlg.resize(1467, 976)
        MainDlg.setStyleSheet("QWidget{\n"
"    font-size: 30px;\n"
"}\n"
"QDialog {\n"
"    background-color:rgb(82, 82, 82);\n"
"}\n"
"QTextEdit {\n"
"    background-color:rgb(42, 42, 42);\n"
"    color: rgb(0, 255, 0);\n"
"}\n"
"QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(0, 0, 0);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(77, 77, 77, 255));\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(100, 100, 100);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"QLabel {\n"
"    color:rgb(255,255,255);\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:rgb(77,77,77);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background:rgb(82, 82, 82);\n"
"}\n"
"QMenuBar::item {\n"
"    color:rgb(223,219,210);\n"
"    spacing: 3px;\n"
"    padding: 1px 4px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background:rgb(115, 115, 115);\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    border-width:2px;\n"
"    border-style:solid;\n"
"    padding-left:18px;\n"
"    padding-right:8px;\n"
"    padding-top:2px;\n"
"    padding-bottom:3px;\n"
"    background:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(78,78,78);\n"
"    padding-left:20px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:10px;\n"
"}\n"
"QMenu{\n"
"    background-color:rgb(78,78,78);\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:rgb(101,101,101);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding:2px;\n"
"    color:rgb(250,250,250);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"      border-top-right-radius:4px;\n"
"   border-top-left-radius:4px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-bottom-color: rgb(101,101,101);\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(101,101,101);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"        margin-top: 1px;\n"
"        margin-right: 1px;\n"
"}\n"
"QCheckBox {\n"
"    color:rgb(223,219,210);\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 150), stop:1 rgba(93, 103, 113, 150));\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(180,180,180);\n"
"      background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QStatusBar {\n"
"    color:rgb(240,240,240);\n"
"}\n"
"QGroupBox{\n"
"    border: none;\n"
"}\n"
"QListWidget{\n"
"    border: 1px solid gray;\n"
"}")
        self.gridLayoutWidget = QtWidgets.QWidget(MainDlg)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 60, 981, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.mainLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)
        self.mainLayout.setVerticalSpacing(20)
        self.mainLayout.setObjectName("mainLayout")
        self.title = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.mainLayout.addWidget(self.title, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.mainLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.mainLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(MainDlg)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(360, 790, 391, 205))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.historyLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.historyLayout.setContentsMargins(10, 10, 10, 10)
        self.historyLayout.setVerticalSpacing(10)
        self.historyLayout.setObjectName("historyLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.historyLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.historyLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.gridLayoutWidget_3)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.historyLayout.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.historyLayout.addWidget(self.tableWidget, 1, 0, 1, 2)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(MainDlg)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(840, 850, 561, 80))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout.setContentsMargins(50, 0, 50, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnFirst = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnFirst.setMinimumSize(QtCore.QSize(55, 0))
        self.btnFirst.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnFirst.setObjectName("btnFirst")
        self.gridLayout.addWidget(self.btnFirst, 0, 0, 1, 1)
        self.btnNext = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnNext.setMinimumSize(QtCore.QSize(55, 0))
        self.btnNext.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnNext.setObjectName("btnNext")
        self.gridLayout.addWidget(self.btnNext, 0, 2, 1, 1)
        self.btnPrev = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnPrev.setMinimumSize(QtCore.QSize(55, 0))
        self.btnPrev.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnPrev.setObjectName("btnPrev")
        self.gridLayout.addWidget(self.btnPrev, 0, 1, 1, 1)
        self.btnLast = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnLast.setMinimumSize(QtCore.QSize(55, 0))
        self.btnLast.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnLast.setObjectName("btnLast")
        self.gridLayout.addWidget(self.btnLast, 0, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(MainDlg)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(1130, 110, 261, 181))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.liveLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.liveLayout.setContentsMargins(10, 10, 10, 10)
        self.liveLayout.setObjectName("liveLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.liveLayout.addWidget(self.label, 0, 0, 1, 1)
        self.chartLayout = QtWidgets.QGridLayout()
        self.chartLayout.setObjectName("chartLayout")
        self.liveLayout.addLayout(self.chartLayout, 0, 1, 1, 1)
        self.liveLayout.setColumnStretch(0, 1)
        self.liveLayout.setColumnStretch(1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(MainDlg)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(110, 640, 691, 113))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.actionLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.actionLayout.setContentsMargins(10, 10, 10, 10)
        self.actionLayout.setObjectName("actionLayout")
        self.btnUpload = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnUpload.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnUpload.setObjectName("btnUpload")
        self.actionLayout.addWidget(self.btnUpload, 0, 1, 1, 1)
        self.btnExit_1 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnExit_1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnExit_1.setObjectName("btnExit_1")
        self.actionLayout.addWidget(self.btnExit_1, 0, 2, 1, 1)
        self.btnNew = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnNew.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnNew.setObjectName("btnNew")
        self.actionLayout.addWidget(self.btnNew, 0, 0, 1, 1)
        self.btnStart = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnStart.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnStart.setObjectName("btnStart")
        self.actionLayout.addWidget(self.btnStart, 1, 0, 1, 1)
        self.btnBlur = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnBlur.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnBlur.setCheckable(True)
        self.btnBlur.setObjectName("btnBlur")
        self.actionLayout.addWidget(self.btnBlur, 1, 1, 1, 1)
        self.btnExit_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnExit_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnExit_2.setObjectName("btnExit_2")
        self.actionLayout.addWidget(self.btnExit_2, 1, 2, 1, 1)

        self.retranslateUi(MainDlg)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainDlg)

    def retranslateUi(self, MainDlg):
        _translate = QtCore.QCoreApplication.translate
        MainDlg.setWindowTitle(_translate("MainDlg", "Dialog"))
        self.title.setText(_translate("MainDlg", "Medical Research Project"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainDlg", "History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainDlg", "Live"))
        self.label_3.setText(_translate("MainDlg", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainDlg", "No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainDlg", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainDlg", "SurName"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainDlg", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainDlg", "Duration"))
        self.btnFirst.setText(_translate("MainDlg", "<<"))
        self.btnNext.setText(_translate("MainDlg", ">"))
        self.btnPrev.setText(_translate("MainDlg", "<"))
        self.btnLast.setText(_translate("MainDlg", ">>"))
        self.label_4.setText(_translate("MainDlg", "Page"))
        self.btnUpload.setText(_translate("MainDlg", "Upload"))
        self.btnExit_1.setText(_translate("MainDlg", "Exit"))
        self.btnNew.setText(_translate("MainDlg", "New "))
        self.btnStart.setText(_translate("MainDlg", "Start"))
        self.btnBlur.setText(_translate("MainDlg", "Blur"))
        self.btnExit_2.setText(_translate("MainDlg", "Exit"))
